# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-09 01:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start_date', models.DateField(default=datetime.date(2016, 10, 9))),
                ('end_date', models.DateField(blank=True, null=True)),
                ('turn_player', models.CharField(blank=True, max_length=64, null=True)),
                ('turn_phase', models.CharField(blank=True, max_length=64, null=True)),
                ('fortifies_used', models.IntegerField(blank=True, null=True)),
                ('fortifies_remaining', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(blank=True, null=True)),
                ('action_type', models.CharField(blank=True, max_length=64, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Game')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('radius', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('side', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('columns', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Game')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('row', models.IntegerField(blank=True, null=True)),
                ('column', models.IntegerField(blank=True, null=True)),
                ('terrain', models.CharField(blank=True, max_length=64, null=True)),
                ('terrain_color', models.CharField(blank=True, max_length=64, null=True)),
                ('owner', models.CharField(blank=True, max_length=64, null=True)),
                ('onwer_color', models.CharField(blank=True, max_length=64, null=True)),
                ('border_n', models.CharField(blank=True, max_length=64, null=True)),
                ('border_s', models.CharField(blank=True, max_length=64, null=True)),
                ('border_ne', models.CharField(blank=True, max_length=64, null=True)),
                ('border_nw', models.CharField(blank=True, max_length=64, null=True)),
                ('border_se', models.CharField(blank=True, max_length=64, null=True)),
                ('border_sw', models.CharField(blank=True, max_length=64, null=True)),
                ('tile_text', models.CharField(blank=True, max_length=64, null=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Map')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='gamelog',
            name='tile_effected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tile_effected', to='map.Tile'),
        ),
    ]
