# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 16:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('TA', 'Tile Assignment'), ('MISC', 'Miscellaneous'), ('ATT', 'Attack'), ('PLACE', 'Unit Placement'), ('MOVE', 'Moving Units'), ('FORT', 'Fortify Unit'), ('BEGIN', 'Begin Turn'), ('END', 'End Turn')], default='MISC', max_length=5)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('radius', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('side', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('columns', models.IntegerField(blank=True, null=True)),
                ('fortifies_used', models.IntegerField(blank=True, null=True)),
                ('fortifies_remaining', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('invite_phase', 'Player invite phase'), ('playing', 'Game is in session'), ('ended', 'Game has ended')], default='invite_phase', max_length=12)),
                ('turn_phase', models.CharField(choices=[('unit_placement', 'Unit placement phase'), ('attack', 'Attack phase'), ('fortity', 'Unit fortification phase')], default='unit_placement', max_length=14)),
                ('turn_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='GameMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('membership_type', models.CharField(choices=[('invited', 'Invited to Game'), ('accepted', 'Accepted Invite'), ('declined', 'Declined Invite')], default='invited', max_length=8)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('row', models.IntegerField(blank=True, null=True)),
                ('column', models.IntegerField(blank=True, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('terrain', models.CharField(blank=True, default='grassland', max_length=64, null=True)),
                ('terrain_color', models.CharField(blank=True, default='green', max_length=64, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('moisture', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('owner_color', models.CharField(blank=True, max_length=64, null=True)),
                ('border_n', models.CharField(blank=True, max_length=64, null=True)),
                ('border_s', models.CharField(blank=True, max_length=64, null=True)),
                ('border_ne', models.CharField(blank=True, max_length=64, null=True)),
                ('border_nw', models.CharField(blank=True, max_length=64, null=True)),
                ('border_se', models.CharField(blank=True, max_length=64, null=True)),
                ('border_sw', models.CharField(blank=True, max_length=64, null=True)),
                ('tile_text', models.CharField(blank=True, max_length=64, null=True)),
                ('highlighted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Game')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Game'),
        ),
        migrations.AddField(
            model_name='action',
            name='tile_acting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tile_acting', to='map.Tile'),
        ),
        migrations.AddField(
            model_name='action',
            name='tile_effected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tile_effected', to='map.Tile'),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
