# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-05 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='moisture',
        ),
        migrations.AlterField(
            model_name='tile',
            name='border_n',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='tile',
            name='border_ne',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='tile',
            name='border_nw',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='tile',
            name='border_s',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='tile',
            name='border_se',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='tile',
            name='border_sw',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='tile',
            name='owner_color',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tile_text',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
