# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170505_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='highlight_color',
            field=models.CharField(default='', max_length=12),
        ),
    ]
