# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-11 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20161111_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gamelog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 11, 20, 37, 52, 339326, tzinfo=utc), null=True),
        ),
    ]
