# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-11 21:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20161111_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 11, 21, 46, 25, 828319, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='gamemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
