# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20161117_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='action_type',
            field=models.CharField(choices=[('TA', 'Tile Assignment'), ('MISC', 'Miscellaneous')], default='MISC', max_length=4),
        ),
    ]
