# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20161117_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tile',
            old_name='onwer_color',
            new_name='owner_color',
        ),
        migrations.AddField(
            model_name='tile',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
