# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20161128_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
