# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_tile_highlighted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameLog',
            new_name='Action',
        ),
    ]
