# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20161129_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='game',
        ),
        migrations.AddField(
            model_name='action',
            name='map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.Map'),
            preserve_default=False,
        ),
    ]
