# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20161129_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemembership',
            name='email',
            field=models.EmailField(default='ACC', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemembership',
            name='membership_type',
            field=models.CharField(choices=[('INV', 'Game Invite'), ('ACC', 'Accepted Invite'), ('DEC', 'Declined Invite')], default='INV', max_length=4),
        ),
        migrations.AlterField(
            model_name='tile',
            name='terrain',
            field=models.CharField(blank=True, default='grassland', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tile',
            name='terrain_color',
            field=models.CharField(blank=True, default='green', max_length=64, null=True),
        ),
    ]
