# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20161130_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemembership',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
