# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_auto_20161130_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemembership',
            name='membership_type',
            field=models.CharField(choices=[('invite', 'Game Invite'), ('accepted', 'Accepted Invite'), ('declined', 'Declined Invite')], default='invite', max_length=8),
        ),
    ]
