# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_action_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='tile_acting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tile_acting', to='map.Tile'),
        ),
    ]
