# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_auto_20161206_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('TA', 'Tile Assignment'), ('MISC', 'Miscellaneous'), ('ATT', 'Attack'), ('PLACE', 'Unit Placement'), ('MOVE', 'Moving Units'), ('FORT', 'Fortify Unit'), ('BEGIN', 'Begin Turn'), ('END', 'End Turn')], default='MISC', max_length=5),
        ),
    ]
