# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_auto_20161219_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn_phase',
            field=models.CharField(choices=[('unit_placement', 'Unit placement phase'), ('attack', 'Attack phase'), ('fortity', 'Unit fortification phase')], default='unit_placement', max_length=14),
        ),
    ]
