# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-01 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_auto_20161219_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='game',
        ),
        migrations.RemoveField(
            model_name='action',
            name='map',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='map',
        ),
        migrations.AddField(
            model_name='action',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='columns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='radius',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='side',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tile',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tile',
            name='game',
            field=models.ForeignKey(default=65, on_delete=django.db.models.deletion.CASCADE, to='map.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tile',
            name='moisture',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
